---
title: "luca_aucell_hierfit"
author: "duygu_k"
date: "2024-08-29"
output: html_document
---

```{r}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.path = "figures/"
)
```

## Packages and Libraries;

```{r}
library(tidyverse)

httpgd::hgd()

```

```{r}
library(Seurat)

#install.packages("devtools")
library(devtools)

devtools::install_github("yasinkaymaz/HieRFIT")

library(HieRFIT)

#Note: Installing additional R packages are recommended: DiagrammeR, e1071, alluvial, and ggalluvial
```



## The Data;

```{r}

luca <- readRDS("data/local.rds")

```

## Subsetting The Data

```{r}

#Subsetting the only macrophages
luca_macs <- subset(luca, ann_fine %in% c("Macrophage alveolar", "Macrophage"))
saveRDS(luca_macs, "data/luca_macs_subset.rds")

```

## Subtypes & Barcodes

### Subtypes

```{r}

#Labels with max AUCell scores
subtypes <- read.csv("data/subtype_matrix.csv")
#colnames(subtypes) <- c("Barcodes", "Subtypes")
colnames(subtypes)[colnames(subtypes) == "X"] <- "Barcodes"

luca_m <- subset(luca_macs, cells = subtypes$Barcodes)

luca_m@meta.data <- cbind(luca_m@meta.data, subtypes)
#colnames(luca_m@meta.data)[colnames(luca_m@meta.data) == "subtypes$Subtypes"] <- "Subtypes"

```
### Barcodes

```{r}

#Barcodes of top250 cells from each subtypes
Angio_TAMs_barcodes <- read_csv("data/Angio_TAMs_barcodes.csv")
IFN_TAMs_barcodes <- read_csv("data/IFN_TAMs_barcodes.csv")
Inflam_TAMs_barcodes <- read_csv("data/Inflam_TAMs_barcodes.csv")
LA_TAMs_barcodes <- read_csv("data/LA_TAMs_barcodes.csv")
Prolif_TAMs_barcodes <- read_csv("data/Prolif_TAMs_barcodes.csv")
Reg_TAMs_barcodes <- read_csv("data/Reg_TAMs_barcodes.csv")
RTM_TAMs_barcodes <- read_csv("data/RTM_TAMs_barcodes.csv")

barcodes <- list(Angio_TAMs_barcodes, IFN_TAMs_barcodes, Inflam_TAMs_barcodes, LA_TAMs_barcodes, 
                 Prolif_TAMs_barcodes, Reg_TAMs_barcodes, RTM_TAMs_barcodes)

barcodes_df <- do.call(rbind, barcodes)


```

#### Training and Query Dataset for HieRFIT Model;

```{r}

#Training Dataset;
luca_mod <- subset(luca_m, cells = barcodes_df$Barcodes)

#Query Dataset;
luca_new <- subset(luca_m, cells = setdiff(Cells(luca_m), barcodes_df$Barcodes))

```

Reference dataset
```{r}
luca_mod
```


```{r}

#Saving the objects
saveRDS(luca_mod, file = "data/luca_hierfit_training_data.rds")
saveRDS(luca_new, file = "data/luca_hierfit_query_data.rds")

```



## HieRFIT Model

### Libraries

```{r}

#library(Seurat)

#install.packages("devtools")
#library(devtools)

#devtools::install_github("yasinkaymaz/HieRFIT")

#library(HieRFIT)

install.packages("DiagrammeR")
library(DiagrammeR)

install.packages("e1017") #might not work
library(e1017)

install.packages("alluvial")
library(alluvial)

library(ggplot2)

install.packages("ggalluvial")
library(ggalluvial)

```

### Create The HieRFIT Model


```{r}

refmod <- CreateHieR(RefData = luca_mod[["RNA"]]@data,
                     ClassLabels = luca_mod@meta.data$Subtype,
                     species = "hsapiens")

#Saving the model
SaveHieRMod(refMod = refmod, filePrefix = "data/Luca_Subtype_HierMod")

```


```{r}

PlotTopoNodeAcc(refMod = refmod)

```


### Reannotation of Query Data with HieRFIT Model;

```{r}

#if you are using a pre-trained model:
#refmod <- readRDS("data/Luca_Subtype_HierMod.RDS")

#Project the cell class labels on the new dataset:
hierObj <- HieRFIT(Query = luca_new[["RNA"]]@data, refMod = refmod)

```


```{r}
hierObj <- readRDS("luca_query_hierObj.rds")
```


```{r}

PlotBarStats(HieRobj = hierObj)

```

```{r}

PlotTopoStats(HieRobj = hierObj)

```


```{r echo=FALSE, fig.width=6, fig.height=4}

CrossCheck(HieRobj = hierObj, Prior = luca_new@meta.data$ann_fine)

```


Adding projection cell types to luca metadata;

```{r}

luca_new@meta.data <- cbind(luca_new@meta.data, hierObj@Evaluation$Projection)

colnames(luca_new@meta.data)[colnames(luca_new@meta.data) == "hierObj@Evaluation$Projection"] <- "Projection_CellType"

saveRDS(luca_new, file = "data/luca_query_reannotated.rds")

```



## Saving for scCODA

```{r}

#ayrı bie df olarak kaydedip, barcode'ları kolon olarak ekle, pythona geçince rownmaes olarak atarsın, ona göre subset yapılabilir

write_csv(hierObj@Evaluation, file = "hierobj_evaluatio.csv", row.names=T)
write.csv(hierObj@Evaluation, file = "hierobj_evaluatio.csv", row.names=T)

```

Count matrix for scCODA
```{r}
# Meta veri çerçevesini al
meta_data <- luca_new@meta.data

# Hücre türü ve örnek bilgilerini içeren veri çerçevesi oluştur
df <- meta_data[, c("sample", "Projection_CellType")]

# Hücre türü ve örnek bazında hücre sayılarını gruplandırma
cell_counts <- table(df$sample, df$Projection_CellType)

# Count matrix olarak döndür
count_matrix <- as.matrix(cell_counts)

# Count matrix'e göz atma
print(count_matrix)

#Saving the coount matrix
write.csv(count_matrix, file = "luca_7macs_sccoda_count_matrix.csv")




#sample-origin df 
df2 <- meta_data[, c("sample", "origin")]
osamp <- table(df2$sample, df2$origin)
osamp <- as.data.frame(osamp)
osamp <- osamp[osamp$Freq != 0 ,]
osamp <- osamp[, -3]
colnames(osamp)[colnames(osamp) == "Var1"] <- "sample"
colnames(osamp)[colnames(osamp) == "Var2"] <- "origin"
write.csv(osamp, file = "luca_7macs_sccoda_sample_origin.csv")



```








